name: Sistem Absensi

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  proccess-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, mysql

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Deployment Commands
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            cd ~/employee-absences
            git reset --hard
            git pull origin main

            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan optimize

            npm install
            npm run build

            sudo chmod -R 775 storage bootstrap/cache
            sudo chown -R www-data:www-data storage bootstrap/cache

            # Restart queue worker (pakai nohup supaya jalan di background)
            pkill -f "artisan queue:work" || true
            nohup php artisan queue:work --daemon --tries=3 > storage/logs/queue.log 2>&1 &
          EOF
