name: Sistem Absensi

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  proccess-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, mysql

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Deployment Commands
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd ~/employee-absences
            git add .
            git commit -m "update from server"
            git pull origin main
            composer install
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan db:seed
            nohup php artisan queue:work > /dev/null 2>&1 &
          EOF
